services:
    vue:
      build: ./vue/
      ports:
        - 8080:8080
      volumes:
        - ./vue/app:/app
      stdin_open: true
      tty: true
      depends_on:
        - rails
    rails:
      build: ./rails/
      ports:
        - 3000:3000
      volumes:
        - ./rails:/app
      depends_on:
        - db
      tty: true
      stdin_open: true
    db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: password
      ports:
        - '3306:3306'
      volumes:
        - ./db/mysql:/var/lib/mysql
    swagger-ui:
      image: swaggerapi/swagger-ui
      ports:
        - 8080:8080
      volumes:
        - ./swagger/openapi.yaml:/usr/share/nginx/html/openapi.yaml
      environment:
        API_URL: openapi.yaml
